<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="Humanizer.Core" Version="3.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.0.4" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="1.8.1" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50" />
    <PackageVersion Include="Npgsql" Version="10.0.2" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageVersion Include="PANiXiDA.Core.Application" Version="2.0.4" />
    <PackageVersion Include="PANiXiDA.Core.Domain" Version="2.0.1" />
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="FluentAssertions" Version="8.9.0" />
  </ItemGroup>
</Project>
