<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>true</IsPackable>

        <AssemblyName>PANiXiDA.Core.Infrastructure.Persistence.Ef</AssemblyName>

        <PackageId>PANiXiDA.Core.Infrastructure.Persistence.Ef</PackageId>
        <Description>Core infrastructure abstractions and utilities for Entity Framework Core persistence adapters.</Description>
        <PackageTags>dotnet;efcore;entity-framework-core;persistence;infrastructure;repository;unit-of-work;ddd;cqrs</PackageTags>

        <RepositoryUrl>https://github.com/panixida-dotnet-core/infrastructure-persistence-ef</RepositoryUrl>
        <PackageProjectUrl>https://github.com/panixida-dotnet-core/infrastructure-persistence-ef</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PANiXiDA.Core.Infrastructure.Persistence.Ef.UnitTests" />
        <InternalsVisibleTo Include="PANiXiDA.Core.Infrastructure.Persistence.Ef.IntegrationTests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="Humanizer.Core" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Nerdbank.GitVersioning">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="PANiXiDA.Core.Application" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../PANiXiDA.Core.Infrastructure.Persistence.Ef.Generators/PANiXiDA.Core.Infrastructure.Persistence.Ef.Generators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all" />
        <None Include="../PANiXiDA.Core.Infrastructure.Persistence.Ef.Generators/bin/$(Configuration)/netstandard2.0/PANiXiDA.Core.Infrastructure.Persistence.Ef.Generators.dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
    </ItemGroup>
</Project>
